name: Netlify Deploy

on:
  issues:
    types: [opened, edited, closed, deleted, reopened, labeled, unlabeled]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Netlify Hook
      run: curl -X POST ${{ secrets.netlify_rebuild }}
    - name: Trigger Vercel Hook
      run: curl -X POST ${{ secrets.ISSUES_VERCEL }}
